# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- release

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          valsquad.azurecr.io/digital-workspace-api
    - task: PowerShell@2
      env:
        USERNAME: $(username)
        PASSWORD: $(password)
      inputs:
        targetType: 'inline'
        script: |
          az login -u $env:USERNAME -p $env:PASSWORD
          az acr login --name valsquad
          docker push valsquad.azurecr.io/digital-workspace-api