# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- release

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          valsquad.azurecr.io/digital-workspace-api
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
          $secret = "$(password)"
          $user = "$(username)"
          $securePassword = ConvertTo-SecureString "$secret" -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential($user, $securePassword)
          Login-AzAccount -Credential $credentials
          Connect-AzContainerRegistry -Name valsquad
          docker push valsquad.azurecr.io/digital-workspace-api