export enum LEAVE_STATUS {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  ADDITIONAL_INFO = 'ADDITIONAL_INFO',
}

export enum ACCRUAL_ENUM {
  YEARLY = 'YEARLY',
  MONTHLY = 'MONTHLY',
}
