export enum ENV_VARIABLE_NAMES {
  LOCAL_MONGO_DB = 'LOCAL_MONGO_DB',
  WEATHER_API = 'WEATHER_API',
  WEATHER_API_KEY = 'WEATHER_API_KEY',
  PRAYER_API = 'PRAYER_API',
  CURRENCY_API = 'CURRENCY_API',
}
