export enum ENV_VARIABLE_NAMES {
  LOCAL_MONGO_DB = 'LOCAL_MONGO_DB',
  WEATHER_API = 'WEATHER_API',
  WEATHER_API_KEY = 'WEATHER_API_KEY',
  PRAYER_API = 'PRAYER_API',
  CURRENCY_API = 'CURRENCY_API',
  JWT_SECRET = 'JWT_SECRET',
}

export enum LangEnum {
  EN = 'EN',
  AR = 'AR',
}

export const GENDER = ['M', 'F'];
